---
galaxy_info:
  author: Rafik Bahri
  description: Cloud Engineer
  company: Freelance
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - php
