---
glpi_version: "10.0.19"
glpi_domain: "glpi-alb-2032728420.eu-west-3.elb.amazonaws.com"
glpi_db_host: "glpi-db.cly8eoseg8e5.eu-west-3.rds.amazonaws.com"
glpi_db_port: 3306
glpi_db_name: "glpi"
glpi_db_user: "glpi_user"
glpi_db_password: "glpi_password"
glpi_timezone: "Europe/Paris"
glpi_upload_max_filesize: "20M"
glpi_post_max_size: "20M"
glpi_max_execution_time: 60
glpi_memory_limit: "256M"
glpi_max_input_vars: 5000
glpi_session_cookie_httponly: "On"
glpi_upgrade_packages: true
glpi_required_packages:
  - apache2
  - php
  - php-apcu
  - php-cli
  - php-common
  - php-curl
  - php-gd
  - php-imap
  - php-ldap
  - php-mysql
  - php-xmlrpc
  - php-xml
  - php-mbstring
  - php-bcmath
  - php-intl
  - php-zip
  - php-redis
  - php-bz2
  - libapache2-mod-php
  - php-soap
  - php-cas
