---
- name: Install requirements
  ansible.builtin.include_tasks: requirements.yml

- name: Configure storage
  ansible.builtin.include_tasks: storage.yml

- name: Configure server
  ansible.builtin.include_tasks: server.yml

- name: Install
  ansible.builtin.include_tasks: install.yml
