---
- name: Create ext4 filesystems
  community.general.filesystem:
    fstype: ext4
    dev: "{{ item.device }}"
    opts: -L "{{ item.label }}"
  loop:
    - { device: '/dev/nvme1n1', label: 'glpi-config' }
    - { device: '/dev/nvme2n1', label: 'glpi-data' }
    - { device: '/dev/nvme3n1', label: 'glpi-logs' }

- name: Create mount points for volumes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /mnt/glpi-config
    - /mnt/glpi-data
    - /mnt/glpi-logs

# FIX: Always changed
- name: Mount filesystems to directories
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: ext4
    opts: defaults,nofail
    state: mounted
  loop:
    - { path: '/mnt/glpi-config', src: '/dev/nvme1n1' }
    - { path: '/mnt/glpi-data', src: '/dev/nvme2n1' }
    - { path: '/mnt/glpi-logs', src: '/dev/nvme3n1' }

- name: Add EBS volumes to fstab for persistence
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: ext4
    opts: defaults,nofail
    dump: '0'
    passno: '2'
    state: present
  loop:
    - { path: '/mnt/glpi-config', src: '/dev/nvme1n1' }
    - { path: '/mnt/glpi-data', src: '/dev/nvme2n1' }
    - { path: '/mnt/glpi-logs', src: '/dev/nvme3n1' }

- name: Set ownership for volumes
  ansible.builtin.file:
    path: "{{ item }}"
    owner: www-data
    group: www-data
    recurse: true
    mode: '0755'
  loop:
    - /mnt/glpi-config
    - /mnt/glpi-data
    - /mnt/glpi-logs

- name: Create directories as symlinks to volumes
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    owner: www-data
    group: www-data
  loop:
    - { src: '/mnt/glpi-config', dest: '/etc/glpi' }
    - { src: '/mnt/glpi-data', dest: '/var/lib/glpi' }
    - { src: '/mnt/glpi-logs', dest: '/var/log/glpi' }

- name: Verify symlinks are created correctly
  ansible.builtin.stat:
    path: "{{ item }}"
  register: symlink_check
  loop:
    - /etc/glpi
    - /var/lib/glpi
    - /var/log/glpi

- name: Display symlink verification
  ansible.builtin.debug:
    msg: "{{ item.item }} -> {{ item.stat.lnk_target if item.stat.islnk else 'NOT A SYMLINK' }}"
  loop: "{{ symlink_check.results }}"
