---
- name: Create filesystems
  become: true
  community.general.filesystem:
    fstype: ext4
    dev: "{{ item.device }}"
    opts: -L "{{ item.label }}"
  loop:
    - { device: '/dev/nvme1n1', label: 'glpi-config' }
    - { device: '/dev/nvme2n1', label: 'glpi-data' }
    - { device: '/dev/nvme3n1', label: 'glpi-logs' }

- name: Create mount points for volumes
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /mnt/glpi-config
    - /mnt/glpi-data
    - /mnt/glpi-logs

- name: Mount filesystems to directories
  become: true
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: ext4
    dump: '0'
    passno: '2'
    opts: "defaults,nofail"
    state: mounted
  loop:
    - { path: '/mnt/glpi-config', src: '/dev/nvme1n1' }
    - { path: '/mnt/glpi-data', src: '/dev/nvme2n1' }
    - { path: '/mnt/glpi-logs', src: '/dev/nvme3n1' }

- name: Set ownership for volumes
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    owner: www-data
    group: www-data
    recurse: true
    mode: '0755'
  loop:
    - /mnt/glpi-config
    - /mnt/glpi-data
    - /mnt/glpi-logs

- name: Create directories as symlinks to volumes
  become: true
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    owner: www-data
    group: www-data
  loop:
    - { src: '/mnt/glpi-config', dest: '/etc/glpi' }
    - { src: '/mnt/glpi-data', dest: '/var/lib/glpi' }
    - { src: '/mnt/glpi-logs', dest: '/var/log/glpi' }
