---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: true

- name: Install PHP packages
  ansible.builtin.apt:
    name: "{{ php_packages }}"
    state: present
