---
galaxy_info:
  author: Rafik Bahri
  description: Role to install and configure Apache2
  company: Freelance
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - web
    - apache
    - http
dependencies: []
